default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  postgres_password: '{{ cookiecutter.postgres_password }}'
  postgres_server: '{{ cookiecutter.postgres_server }}'
  _template: ./
