version: '3.7'

services:

  backend:
    container_name: {{ cookiecutter.project_slug }}_backend:latest
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - USER_SERVICE_HOST_URL=http://{{ cookiecutter.project_slug }}_backend:8000/api/v1/{{ cookiecutter.project_slug }}/

  db:
    container_name: {{ cookiecutter.project_slug }}_db
    image: postgres:12.2
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: {{ cookiecutter.project_slug }}_nginx
    restart: always
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.config
    ports:
      - 80:80
    env_file:
      - .env

volumes:
  app-db-data:
